Please check if PyBossa is running and properly set. Your current settings:
<ul>
  <li><code>PYBOSSA_URL = {{ pybossa_url }}</code></li>
  <li><code>PYBOSSA_PROJECT_ID = {{ project_id }}</code></li>
</ul>

<ol>
  <li>
    Launch locally <a href="http://docs.pybossa.com/">PyBossa</a> or use prepared endpoint
    (i.e. <a href="https://crowdcrafting.org/">crowdcrafting</a>)
  </li>
  <li>Sign in to <a href="{{ pybossa_url }}/account/signin">PyBossa</a></li>
  <li>
    <a href="{{ pybossa_url }}/project/new">Create project</a> in PyBossa and check if its <a href="{{ pybossa_url }}/api/project/{{ project_id }}">API</a> is available
  </li>
  <li>in settings.py:</li>
  <pre><code>
    MOONSHEEP_TASK_SOURCE = 'pybossa'
    PYBOSSA_URL = 'http://localhost:&#123;&#123;pybossa-port&#125;&#125;/'
    PYBOSSA_PROJECT_ID = 1
    PYBOSSA_API_KEY = os.environ.get('PYBOSSA_API_KEY')
  </code></pre>
</ol>